### ISSUE TITLE
Write Selenium Tests

### ISSUE THREAD

**Issue by kyliesanderson** [Daniel9650/idb#21]
By this iteration, the required functionality includes:
- The model grid pages should all load and have unbroken links to their respective instance pages
- Instance pages should link to each other whenever possible without any broken links (internal or out-going)
- Navbar works fine from any page
- Going back and forth in the navigation history does not break the website
* Note that you do not have to test all of this functionality for every single possible instance page as that would be intractable for larger databases. Given that your pages are all generated in some standard manner, it could be assumed that testing one instance page (that contains all the possible elements that any instance page of that model could have) would sufficiently test all of the instance pages for that model.
 

Quality of the frontend GUI tests.

create acceptance tests of the GUI
use Selenium

store in frontend/guitests.py

**Comment by Daniel9650** [comment]
Estimated Time: 3 hours
Actual Time;

**Comment by kyliesanderson** [comment]
All 10 tests completed and passing
Actual Time: 4.5 hours
-Waiting time for tests to run 
-Learning curve working with Selenium
