### ISSUE TITLE
Create New API Calls for Filtering/Searching/Sorting Results

### ISSUE THREAD

**Issue by kyliesanderson** [Daniel9650/idb#41]
A user should be able to search a model for instances using name, and other attributes. They should also be able to filter existing search results, meaning they should search the result from a previous API call for a new attribute. 

Model pages also need to be sortable by release date and A-Z, both in ascending and descending order.

Estimated Time: 2 hours

**Comment by drewdearing** [comment]
Noticed I wasn't assigned this issue. Strange.

Finished implementing this feature in main.py.
The API calls to sort, filter, and query are done as follows:
api.poptopic.org/model?q=[search]&filter=[column to search]&sort=[sort method:asc or desc]
api.poptopic.org/model/instance/similar_model?q=[search]&filter=[column to search]&sort=[sort method:asc or desc]

pages and items_per_page still apply to these calls as well.

Actual Time: 5 hours
