### ISSUE TITLE
As a user, I would like the page titles to be slightly lower so that the logo does not overlap.

### ISSUE THREAD

**Issue by kattawar** [Daniel9650/idb#54]
Right now most page's titles are being overlapped by the logo. It would look a little nicer if they did not.

**Comment by kyliesanderson** [comment]
Tasks:
Examine title CSS class 
Examine spacing-div class, consider changing padding amount to allow accomodation for logo

Estimated Time: 10 minutes

**Comment by kyliesanderson** [comment]
Estimated Time: 10 minutes
Actual Time: 5 minutes
