### ISSUE TITLE
As a user I would like to see slightly smaller images used

### ISSUE THREAD

**Issue by kattawar** [Daniel9650/idb#55]
When Looking at a page like the movie page for example, some of the images that use words in the cover art get chopped off and the title can't be read. It would be nice if the images were not cropped or just made smaller in order to not slice parts of the title off.

**Comment by kyliesanderson** [comment]
Tasks:
Examine CSS for movie, book, and album images
Look at recommended proportions for movie covers, books, and albums
Modify max-width and max-height properties of CS classes to prevent text cut-off by conforming to proper proportions 

Estimated Time: 30 minutes

**Comment by kyliesanderson** [comment]
We decided to make the images slightly taller, creating square images for the grid pages. This makes all the album artwork visible for the music model, and makes most of the movie and book posters more visible as well. The words are less cutoff and the images are more clear.

Estimated Time: 30 minutes
Actual Time: 20 minutes (includes time for discussion among team)
