### ISSUE TITLE
As a user I would like to get search result either in the order of strongest relevance or separated by type.

### ISSUE THREAD

**Issue by erinjensby** [Daniel9650/idb#56]
Right now, when a user searches the results are returned books, then movies, then music.  It would be nice to either get the results in order of the most relevant regardless of type or get the results in separate paginations so that the user can look at whichever they want.

**Comment by kyliesanderson** [comment]
This sounds like an error when testing this user story, as the sorted results for our global search is already done in order of relevance, not in order of media type. This can be seen when searching the word "Gone", which results in showing the movie "Gone Girl" first, followed by the books "Mighty Jack and the Goblin King" and "Stormbreaker", which both have the word "gone" in their descriptions. So the relevance sort put the media with the word "gone" in the title first, followed by media with "gone" in the description.

**Comment by kyliesanderson** [comment]
We will also be adding a sort dropdown to the search results page so the user can see the default is by relevance and change it if wanted.
