### ISSUE TITLE
As a user I'd like to see the search terms I searched for highlighted in the result page.

### ISSUE THREAD

**Issue by nico1utaustin** [Daniel9650/idb#57]
Right now , nothing is highlighted in the search results. We recommend using react-highlight-words package to do this easily.

**Comment by kyliesanderson** [comment]
Tasks: 
Use mark.js to highlight search term within normal card info: Title, author, topics, director, actors, album, artists.
Add ability to conditionally view part of description to card
Make sure card shows only relevant description information with highlighted words (keep to one line)

Estimated Time: 2 hours

**Comment by kyliesanderson** [comment]
Estimated Time: 2 hours
Actual Time: 2 hours and 15 minutes
