### ISSUE TITLE
As a user I'd like the splash page words to not overlap.

### ISSUE THREAD

**Issue by nico1utaustin** [Daniel9650/idb#58]
Right now some of the titles overlap the underlying text on the splash page and its sometimes hard to read.

**Comment by kyliesanderson** [comment]
Tasks:
Look at CSS classes for carousel text, specifically the transform functions that position the text in the center
Modify transform functions to prevent overlay of text 
Change font-size to max-font-size to allow text to scale, not create two lines for main headline
Look for alternatives to transform functions

Estimated Time: 30 minutes

**Comment by kyliesanderson** [comment]
Estimated Time: 30 minutes
Actual Time: 1 hour
