### ISSUE TITLE
As a user, I would like to be able to search for multiple topics at once.

### ISSUE THREAD

**Issue by erinjensby** [Daniel9650/idb#59]
It would be nice if an or functionality were implemented for the search.  This way the user could search multiple topics and get more google-like results.

**Comment by kyliesanderson** [comment]
Tasks: 
Implement the multiselect option for React Select for TopicFilter.js

Estimated Time: 1 hour

**Comment by kyliesanderson** [comment]
Implemented multiselect for topics for all models. Alterations interfered with url parameters filling filter groups, need to fix. Also need to alter CSS for multiselect if possible.

Time Elapsed: 45 minutes

**Comment by kyliesanderson** [comment]
Fixed automatic population from URL parameters. Added CSS. 

Estimated Time: 1 hour
Actual Time: 2.5 hours
