### ISSUE TITLE
As a user I would like to see more cards per page

### ISSUE THREAD

**Issue by kattawar** [Daniel9650/idb#60]
When looking at any of the various pages that relate Topics, Movies, or Books it would be nice to see a little more than 3 records per page. It would be useful to see closer to 10 cards per category so that more content can be consumed from the page in a quicker manner. Then not as many links would need to be clicked in order to read a decent amount of material.

**Comment by kyliesanderson** [comment]
Added pagination to lists of similar/related media on each instance page. 
Modified cards for related/similar media to look more similar to model cards, showing additional info like topics, author, artists, album, etc. 

Estimated Time: 30 minutes
Actual Time: 30 minutes
