### ISSUE TITLE
As a user the sort by year is a little confusing at first 

### ISSUE THREAD

**Issue by kattawar** [Daniel9650/idb#61]
When clicking on the sort by column it is a little confusing at first when I saw just a big year range, it sort of made me think I was doing a filtering or something like that. It would be nice if it instead said something along the lines of 'Year Low to High' then it would be a little more clear what the selection does when read.

**Comment by kyliesanderson** [comment]
Estimate Time: 5 minutes
Actual Time: 5 minutes
