### ISSUE TITLE
As a user I'd like the pagination component to not have "next" for when there are 0 results

### ISSUE THREAD

**Issue by nico1utaustin** [Daniel9650/idb#62]
For example go to music and filter by Artist: "Weird Al Yankovic" the pagination displays a next button even though there are no results. This could potentially mislead users who think there is a next page.

**Comment by kyliesanderson** [comment]
Fixed by changing pagination to go back to page 1 when a filter is added at a later page, and when filter changes were added to the url. The following times are for those changes, which fixed this also. 

Estimated Time: 2 hours
Actual Time: 20 hours
