### ISSUE TITLE
As a user, I'd like to be able to click anywhere on the trending topics to go to that instance.

### ISSUE THREAD

**Issue by erinjensby** [Daniel9650/idb#63]
Their grid view now allows you to click anywhere on the instance card, the trending topics on the home page still require the user to click on a button below the image and name to go to the link. They should change these to be the same as the cards on the browsing page as they are more functional and the site will have more continuity.

**Comment by kyliesanderson** [comment]
2 Solution options: change trending topics to cards or wrap current topics in anchor

wrapping in anchor is simpler, will take less time, and maintain echo of circle from logo, but creating cards would echo model grid consistency

**Comment by kyliesanderson** [comment]
We chose to change the popular topics to cards so they are easily clickable and more consistent with the model pages. 

Estimated Time: 15 minutes
Actual Time: 15 minutes
